Repository googleinterns/step-2020-wipeout-jr, pull requests merged in 2020-07, with the labels that each got.

#36 Adjusts book class to work with more fields
  portfolio/pom.xml
  portfolio/src/main/java/com/google/sps/data/Book.java
  portfolio/src/main/java/com/google/sps/data/BookReader.java
Labels: cla: no

#39 Add a default value for genre
  portfolio/src/main/java/com/google/sps/data/Book.java
Labels: small bug

#38 BookResponseParser.java
  portfolio/src/main/java/com/google/sps/data/BookResponseParser.java
  portfolio/src/test/java/com/google/sps/BookParserTestFile.json
  portfolio/src/test/java/com/google/sps/BookResponseParserTest.java
Labels: top

#44 Updated validator to use preconditions
  portfolio/src/main/java/com/google/sps/data/BookResponseParser.java
  portfolio/src/test/java/com/google/sps/BookResponseParserTest.java
Labels: small bug

#41 Creates DAO for books in DS
  portfolio/src/main/java/com/google/sps/data/BookDao.java
  portfolio/src/main/java/com/google/sps/data/BookDaoDatastore.java
  portfolio/src/test/java/com/google/sps/BookDaoTest.java
Labels: DAO, datastore

#40 Create BookServiceClient
  portfolio/src/main/java/com/google/sps/data/BookServiceClient.java
  portfolio/src/test/java/com/google/sps/BookServiceClientTest.java
Labels: top

#43 Creates reviewDAODatastore
  portfolio/src/main/java/com/google/sps/data/Book.java
  portfolio/src/main/java/com/google/sps/data/BookReader.java
  portfolio/src/main/java/com/google/sps/data/BookResponseParser.java
  portfolio/src/main/java/com/google/sps/data/Review.java
  portfolio/src/main/java/com/google/sps/data/ReviewDao.java
  portfolio/src/main/java/com/google/sps/data/ReviewDaoDatastore.java
  portfolio/src/test/java/com/google/sps/AuthenticationServletTest.java
  portfolio/src/test/java/com/google/sps/BookDaoTest.java
  portfolio/src/test/java/com/google/sps/BookResponseParserTest.java
  portfolio/src/test/java/com/google/sps/BookServiceClientTest.java
  portfolio/src/test/java/com/google/sps/GenreRecommenderTest.java
  portfolio/src/test/java/com/google/sps/ReviewDaoTest.java
  portfolio/src/test/java/com/google/sps/UserStatusServletTest.java
Labels: DAO, datastore

#46 Book upload utility
  portfolio/src/main/java/com/google/sps/data/BookUploadUtilty.java
  portfolio/src/main/java/com/google/sps/data/MergeBooks.java
  portfolio/src/test/java/com/google/sps/MergeBooksTest.java
Labels: DAO, datastore

#47 Fixed filename error
  portfolio/src/main/java/com/google/sps/data/BookUploadUtility.java
Labels: tiny bug

#37 add user DAO and store on datastore
  portfolio/src/main/java/com/google/sps/data/User.java
  portfolio/src/main/java/com/google/sps/data/UserDao.java
  portfolio/src/main/java/com/google/sps/data/UserDaoDatastore.java
  portfolio/src/main/java/com/google/sps/servlets/AuthenticationServlet.java
  portfolio/src/main/java/com/google/sps/servlets/UploadBookWithListOfFields.java
  portfolio/src/main/java/com/google/sps/servlets/UserInfoServlet.java
  portfolio/src/main/java/com/google/sps/servlets/UserStatusServlet.java
  portfolio/src/main/webapp/app.js
  portfolio/src/main/webapp/book-detail/book-detail.component.js
  portfolio/src/main/webapp/index.html
  portfolio/src/main/webapp/user-auth/user-auth.component.js
  portfolio/src/main/webapp/user-auth/user-auth.module.js
  portfolio/src/main/webapp/user-auth/user-auth.template.html
  portfolio/src/main/webapp/user-info/user-info.component.js
  portfolio/src/main/webapp/user-info/user-info.module.js
  portfolio/src/main/webapp/user-info/user-info.template.html
  portfolio/src/test/java/com/google/sps/AuthenticationServletTest.java
  portfolio/src/test/java/com/google/sps/UserDaoTest.java
  portfolio/src/test/java/com/google/sps/UserStatusServletTest.java
Labels: DAO, datastore

#52 Initialize book upload
  portfolio/src/main/java/com/google/sps/data/MergeBooks.java
  portfolio/src/main/java/com/google/sps/servlets/AdminBookUploadServlet.java
Labels: datastore

#59 Changes the book list to be sourced from DS
  portfolio/src/main/java/com/google/sps/data/BookDao.java
  portfolio/src/main/java/com/google/sps/data/BookDaoDatastore.java
  portfolio/src/main/java/com/google/sps/data/BookEntityParser.java
  portfolio/src/main/java/com/google/sps/servlets/BookServlet.java
  portfolio/src/main/webapp/book-list/book-list.component.js
Labels: datastore, frontend

#60 Changes the book detail source to DS
  portfolio/src/main/java/com/google/sps/servlets/SingleBookServlet.java
  portfolio/src/main/webapp/book-detail/book-detail.component.js
  portfolio/src/main/webapp/book-detail/book-detail.template.html
  portfolio/src/main/webapp/book-list/book-list.template.html
Labels: datastore, frontend

#61 Update app.config.js to have isbn instead of id
  portfolio/src/main/java/com/google/sps/servlets/BookServlet.java
  portfolio/src/main/webapp/app.config.js
  portfolio/src/main/webapp/book-detail/book-detail.component.js
Labels: frontend, small bug

#66 Add background image
  portfolio/src/main/webapp/images/Books_Background.png
Labels: fixes small bug

#67 Deletes local_db.bin
  portfolio/WEB-INF/appengine-generated/local_db.bin
Labels: fixes small bug

#62 Adds recommendations and reviews to book detail page
  portfolio/src/main/java/com/google/sps/servlets/BookReviewServlet.java
  portfolio/src/main/java/com/google/sps/servlets/RecommendBookServlet.java
  portfolio/src/main/webapp/book-detail/book-detail.component.js
  portfolio/src/main/webapp/book-detail/book-detail.template.html
  portfolio/src/main/webapp/book-list/book-list.template.html
Labels: front-end
